<?php

declare(strict_types=1);

namespace Monadial\Nexus\Ddd\Bus\Routing;

use Nette\PhpGenerator\Dumper;
use Nette\PhpGenerator\Literal;
use ReflectionClass;
use RuntimeException;

use function array_keys;
use function dirname;
use function file_put_contents;
use function filemtime;
use function hash;
use function is_file;
use function ksort;
use function rename;
use function serialize;
use function sort;
use function sprintf;
use function tempnam;

/**
 * @psalm-api
 *
 * Writes a `BusBuildResult` to disk as an opcache-friendly
 * `CompiledBusBootSnapshot` PHP file. Extracted from `BusBuilder` so the
 * boot-time reflection orchestrator stays focused on its single
 * responsibility (panel Fowler F1).
 *
 * The output is written atomically: a tmp file in the destination
 * directory + `rename()`.
 */
final class CompiledBusBootWriter
{
    /**
     * @throws RuntimeException when the snapshot file cannot be written
     */
    public function writeTo(string $path, BusBuildResult $result): void
    {
        $code = $this->renderSnapshot($result);

        $tmp = tempnam(dirname($path), 'ddd-routes-compile-');

        if ($tmp === false) {
            throw new RuntimeException(sprintf('Could not create temp file in directory of %s', $path));
        }

        if (file_put_contents($tmp, $code) === false) {
            throw new RuntimeException(sprintf('Could not write snapshot to temp file %s', $tmp));
        }

        if (!rename($tmp, $path)) {
            throw new RuntimeException(sprintf('Could not rename %s to %s', $tmp, $path));
        }
    }

    /**
     * Emit the snapshot as opcache-friendly PHP. Top-level shape:
     *
     *     <?php
     *     declare(strict_types=1);
     *     return new \Monadial\Nexus\Ddd\Bus\Routing\CompiledBusBootSnapshot(
     *         sourceHash: '...',
     *         handlerMap: [...],
     *         entries: [...],
     *     );
     *
     * Uses `Nette\PhpGenerator\Dumper` for scalar/array dumping; attribute
     * instances and `ResolvedAttributesEntry` are emitted via `Dumper::format()`
     * with a `new \FQN(...?:)` template (the `...?:` placeholder expands an
     * associative array as named arguments) and wrapped in `Literal` when
     * placed inside an outer array so `Dumper` inlines them verbatim instead
     * of falling back to `__set_state`-style object dumping.
     */
    private function renderSnapshot(BusBuildResult $result): string
    {
        $dumper = new Dumper();
        $dumper->indentation = '    ';

        $handlerMap = $result->handlerMap;
        ksort($handlerMap);

        $entries = [];

        foreach ($result->index->all() as $messageClass => $entry) {
            $entries[$messageClass] = new Literal($this->renderResolvedAttributesEntry($entry, $dumper));
        }

        ksort($entries);

        return sprintf(
            "<?php\n\ndeclare(strict_types=1);\n\n// Generated by ddd:routes:compile — do not edit by hand.\n// To refresh: bin/console ddd:routes:compile <output-path>.\n\nreturn new \\%s(\n    sourceHash: %s,\n    handlerMap: %s,\n    entries: %s,\n);\n",
            CompiledBusBootSnapshot::class,
            $dumper->dump(self::computeSourceHash($result)),
            $dumper->dump($handlerMap),
            $dumper->dump($entries),
        );
    }

    private function renderResolvedAttributesEntry(ResolvedAttributesEntry $entry, Dumper $dumper): string
    {
        $attributes = [];

        foreach ($entry->attributes as $attrClass => $instance) {
            $attributes[$attrClass] = new Literal($this->renderAttributeInstance($instance, $dumper));
        }

        ksort($attributes);

        return $dumper->format(
            'new \\' . ResolvedAttributesEntry::class . '(...?:)',
            [
                'attributes' => $attributes,
                'authorizeBeforeValidate' => $entry->authorizeBeforeValidate,
                'handlerClass' => $entry->handlerClass,
                'idempotencyOptedOut' => $entry->idempotencyOptedOut,
            ],
        );
    }

    private function renderAttributeInstance(object $instance, Dumper $dumper): string
    {
        $reflection = new ReflectionClass($instance);
        $class = $reflection->getName();
        /** @var array<string, mixed> $args */
        $args = [];

        foreach ($reflection->getProperties() as $property) {
            /** @psalm-suppress MixedAssignment — attribute properties are typed by the attribute class itself */
            $args[$property->getName()] = $property->getValue($instance);
        }

        return $dumper->format('new \\' . $class . '(...?:)', $args);
    }

    /**
     * Compute a fingerprint of the source state that produced this snapshot.
     * Adopters compare this hash against the live builder to detect drift
     * between deploy-time compile and runtime boot. Inputs: sorted handler
     * class list + `composer.lock` mtime (0 when missing).
     */
    private static function computeSourceHash(BusBuildResult $result): string
    {
        $handlers = array_keys($result->handlerMap);
        sort($handlers);
        $lockMtime = is_file('composer.lock')
            ? filemtime('composer.lock')
            : 0;

        return hash('xxh3', serialize([$handlers, $lockMtime]));
    }
}
