/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/persistent-actors',
        'getting-started/concepts',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/overview',
        'tutorials/wallet-app',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/overview',
        'guides/message-design',
        'guides/ask-vs-tell',
        'guides/single-writer-aggregates',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      items: [
        'best-practices/overview',
        'best-practices/when-to-use-actors',
        'best-practices/pooled-connections',
        'best-practices/supervision',
        'best-practices/passivation',
        'best-practices/scaling',
        'best-practices/observability',
        'best-practices/testing',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/nexus-thesis',
        'core-concepts/actors',
        'core-concepts/behaviors',
        'core-concepts/props',
        'core-concepts/supervision',
        'core-concepts/mailboxes',
        'core-concepts/lifecycle',
        'core-concepts/ask-pattern',
        'core-concepts/persistence',
        'core-concepts/passivation',
      ],
    },
    {
      type: 'category',
      label: 'Runtimes',
      items: [
        'runtimes/overview',
        'runtimes/bootstrap',
        'runtimes/runtime-standalone',
        'runtimes/runtime-without-actors',
        'runtimes/fiber',
        'runtimes/swoole',
        'runtimes/step',
      ],
    },
    {
      type: 'category',
      label: 'Scaling',
      items: [
        'scaling/overview',
        'scaling/configuration',
        'scaling/bootstrap',
      ],
    },
    {
      type: 'category',
      label: 'HTTP',
      items: [
        'http/overview',
        'http/getting-started',
        'http/routing',
        'http/handlers',
        'http/auth',
        'http/middleware',
        'http/responses',
        'http/error-handling',
        'http/websockets',
        'http/actors-in-http',
        'http/servers',
        'http/observability',
        'http/production',
        'http/performance',
      ],
    },
    {
      type: 'category',
      label: 'Doctrine',
      items: [
        'doctrine/overview',
        'doctrine/connection-pool',
        'doctrine/entity-manager-pool',
        'doctrine/http-integration',
        'doctrine/entity-behavior',
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [
        'packages/core',
        'packages/runtime',
        'packages/runtime-fiber',
        'packages/runtime-swoole',
        'packages/runtime-step',
        'packages/cluster',
        'packages/worker-pool',
        'packages/worker-pool-swoole',
        'packages/serialization',
        'packages/logger',
        'packages/http',
        'packages/http-ws',
        'packages/http-auth',
        'packages/http-server-swoole',
        'packages/http-server-swoole-threads',
        'packages/persistence',
        'packages/persistence-dbal',
        'packages/persistence-doctrine',
        'packages/doctrine-dbal',
        'packages/doctrine-orm',
        'packages/app',
        'packages/psalm',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/design-philosophy',
        'architecture/internals',
        'architecture/performance',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/development',
        'contributing/roadmap',
      ],
    },
  ],
};

module.exports = sidebars;
