/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'welcome',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/concepts',
        'getting-started/persistent-actors',
        'getting-started/module-selector',
        'getting-started/local-dev-without-docker',
        'getting-started/common-mistakes',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/overview',
        'tutorials/wallet-app',
        'tutorials/tictactoe',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/nexus-thesis',
        'core-concepts/actors',
        'core-concepts/behaviors',
        'core-concepts/props',
        'core-concepts/supervision',
        'core-concepts/mailboxes',
        'core-concepts/lifecycle',
        'core-concepts/ask-pattern',
        'core-concepts/passivation',
        'core-concepts/envelopes',
        'core-concepts/dead-letters',
        'core-concepts/futures',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/overview',
        'guides/message-design',
        'guides/ask-vs-tell',
        'guides/single-writer-aggregates',
        'guides/routing-patterns',
        'guides/fan-out',
        'guides/rate-limiting-actor',
        'guides/saga',
        'guides/standalone-integration',
      ],
    },
    {
      type: 'category',
      label: 'Runtimes',
      items: [
        'runtimes/overview',
        'runtimes/bootstrap',
        'runtimes/standalone',
        'runtimes/fiber',
        'runtimes/swoole',
        'runtimes/step',
        'runtimes/xdebug',
      ],
    },
    {
      type: 'category',
      label: 'HTTP',
      items: [
        'http/overview',
        'http/getting-started',
        'http/routing',
        'http/handlers',
        'http/auth',
        'http/middleware',
        'http/responses',
        'http/error-handling',
        'http/websockets',
        'http/websockets-channel-actors',
        'http/actors-in-http',
        'http/servers',
      ],
    },
    {
      type: 'category',
      label: 'Persistence',
      items: [
        'persistence/overview',
        'persistence/event-sourcing',
        'persistence/durable-state',
        'persistence/snapshots',
        'persistence/single-writer',
        'persistence/stores',
        'persistence/testing',
      ],
    },
    {
      type: 'category',
      label: 'Doctrine',
      items: [
        'doctrine/overview',
        'doctrine/connection-pool',
        'doctrine/entity-manager-pool',
        'doctrine/http-integration',
        'doctrine/entity-behavior',
        'doctrine/migrations',
        'doctrine/second-level-cache',
        'doctrine/fixtures',
      ],
    },
    {
      type: 'category',
      label: 'Scaling & Clustering',
      items: [
        'scaling/overview',
        'scaling/configuration',
        'scaling/bootstrap',
        'scaling/choosing-thread-count',
        'scaling/cross-worker-ask',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/overview',
        'operations/deployment',
        {
          type: 'category',
          label: 'Deployment',
          items: [
            'operations/deployment/docker',
            'operations/deployment/systemd',
            'operations/deployment/kubernetes',
          ],
        },
        'operations/observability',
        'operations/performance-tuning',
        'operations/metrics',
        'operations/graceful-shutdown',
        'operations/sysctls',
        'operations/troubleshooting',
        'operations/runbook',
        'operations/zts-php-setup',
        'operations/swoole-deadlock-detector',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      items: [
        'best-practices/overview',
        'best-practices/when-to-use-actors',
        'best-practices/supervision',
        'best-practices/observability',
        'best-practices/scaling',
        'best-practices/passivation',
        'best-practices/pooled-connections',
        'best-practices/testing',
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Foundation',
          items: [
            'packages/core',
            'packages/runtime',
          ],
        },
        {
          type: 'category',
          label: 'Runtimes',
          items: [
            'packages/runtime-fiber',
            'packages/runtime-swoole',
            'packages/runtime-step',
          ],
        },
        {
          type: 'category',
          label: 'HTTP',
          items: [
            'packages/http',
            'packages/http-ws',
            'packages/http-auth',
            'packages/http-toolkit',
            'packages/http-server-swoole',
            'packages/http-server-swoole-threads',
          ],
        },
        {
          type: 'category',
          label: 'Persistence',
          items: [
            'packages/persistence',
            'packages/persistence-dbal',
            'packages/persistence-doctrine',
          ],
        },
        {
          type: 'category',
          label: 'Doctrine',
          items: [
            'packages/doctrine-dbal',
            'packages/doctrine-orm',
          ],
        },
        {
          type: 'category',
          label: 'Scaling',
          items: [
            'packages/cluster',
            'packages/worker-pool',
            'packages/worker-pool-swoole',
          ],
        },
        {
          type: 'category',
          label: 'Tooling',
          items: [
            'packages/app',
            'packages/logger',
            'packages/serialization',
            'packages/psalm',
            'packages/nexus',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'doc', id: 'reference/overview' },
      items: [
        'reference/overview',
        {
          type: 'category',
          label: 'Front-door classes',
          collapsed: false,
          items: [
            'reference/classes/duration',
            'reference/classes/actor-system',
            'reference/classes/behavior',
            'reference/classes/props',
            'reference/classes/actor-ref',
            'reference/classes/actor-context',
            'reference/classes/behavior-with-state',
            'reference/classes/persistence-id',
            'reference/classes/event-sourced-behavior',
            'reference/classes/durable-state-behavior',
            'reference/classes/effect',
            'reference/classes/event-store',
            'reference/classes/runtime',
            'reference/classes/mailbox-config',
            'reference/classes/envelope',
            'reference/classes/signal',
            'reference/classes/http-app',
            'reference/classes/route-builder',
            'reference/classes/compiled-http-app',
            'reference/classes/websocket-handler',
            'reference/classes/websocket-context',
            'reference/classes/authentication-middleware',
            'reference/classes/requires-auth',
            'reference/classes/worker-node',
            'reference/classes/nexus-app',
          ],
        },
        {
          type: 'category',
          label: 'Catalogs',
          collapsed: false,
          items: [
            'reference/config',
            'reference/system-messages',
            'reference/lifecycle-signals',
            'reference/exceptions',
            'reference/attributes',
            'reference/psalm-rules',
            'reference/gotchas',
          ],
        },
        'reference/internals-appendix',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/design-philosophy',
        'architecture/internals',
        {
          type: 'category',
          label: 'ADRs',
          collapsed: true,
          items: [
            'architecture/adrs/actor-model-architecture',
            'architecture/adrs/immutable-behavior-api',
            'architecture/adrs/dual-runtime-strategy',
            'architecture/adrs/message-serialization',
            'architecture/adrs/multi-process-clustering',
            'architecture/adrs/persistence-event-sourcing',
            'architecture/adrs/remote-ask-protocol',
            'architecture/adrs/worker-pool-cluster-separation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Upgrade & Changelog',
      items: [
        'upgrade/overview',
        'upgrade/upgrade',
      ],
    },
    {
      type: 'category',
      label: 'FAQ & Glossary',
      items: [
        'faq/overview',
        'faq/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/development',
        'contributing/roadmap',
        'contributing/your-first-pr',
        'contributing/release-process',
        'contributing/splitsh',
        'contributing/security',
        'contributing/adding-a-runtime',
        'contributing/adding-a-param-resolver',
        'contributing/adding-a-package',
      ],
    },
  ],
};

module.exports = sidebars;
